name: PlayWright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Install PlayWright browsers
      run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install chromium"
    
    - name: Create videos directory
      run: mkdir -p videos
    
    - name: Run PlayWright tests
      run: mvn test -DsuiteXmlFile=testng-playwright.xml -Dheadless=true
      env:
        DISPLAY: :99
      
    - name: Upload test videos
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-videos
        path: videos/
        retention-days: 7
        
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports
        path: target/surefire-reports/
        retention-days: 7
        
    - name: Upload Maven logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: maven-logs
        path: target/
        retention-days: 7 